name: "Run Julia Benchmarks"
description: "Takes your packages for a jog by running it's Benchmarks"
author: "Alexius Wadell"

branding:
  icon: activity
  color: purple

inputs:
  prefix:
    description: "Prefix to be inserted before the julia command"
    default: ""
    required: false
  options:
    description: "Additional command line flags to pass to the julia command. e.g. `-O3`"
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: 🏃 Install PkgJogger
      id: install_pkgjogger
      run: >
        julia --color=yes --eval
        'using Pkg; Pkg.Registry.update(); Pkg.develop(PackageSpec(; name="PkgJogger", path="${{ github.action_path }}"))'
      shell: bash

    - name: ⏱  Run Benchmarks
      id: run_benchmarks
      run: >
        ${{ inputs.prefix }} julia --color=yes
        ${{ inputs.options }} --eval 'using PkgJogger; PkgJogger.ci()'
      shell: bash
