name: "Run Julia Benchmarks"
description: "Takes your packages for a jog by running it's Benchmarks"
author: "Alexius Wadell"

branding:
  icon: activity
  color: purple

inputs:
  prefix:
    description: "Prefix to be inserted before the julia command"
    default: ""
    required: false
  options:
    description: "Additional command line flags to pass to the julia command. e.g. `-O3`"
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: 🏃 Install PkgJogger
      id: install_pkgjogger
      run: >
        PKG_JOGGER_ENV=$(mktemp --directory);
        echo "env=$PKG_JOGGER_ENV" >> $GITHUB_STATE;
        julia --color=yes --project="$PKG_JOGGER_ENV" --eval
        'using Pkg; Pkg.develop(name="PkgJogger", path="${{ github.action_path }}")'
      shell: bash

    - name: ⏱ Run Benchmarks
      id: run_benchmarks
      run: >
        ${{ inputs.prefix }} julia --project="${{ steps.install_pkgjogger.outputs.env }}" --color=yes
        ${{ inputs.options }} --eval 'using PkgJogger; PkgJogger.ci()'
      shell: bash

    - name: 🧹 Cleanup PkgJogger
      id: Cleanup
      run: rm -rf "${{ steps.install_pkgjogger.outputs.env }}"
      shell: bash
