name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '*'     # Latest Release
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-uploadcoveralls@v1
        continue-on-error: true
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  legacy:
    name: Test Min Compat Bounds
    runs-on: ubuntu-latest
    steps:
    - uses: julia-actions/julia-downgrade-compat@v1
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v2
      with:
        version: 1.9
    - uses: julia-actions/cache@v1
    - uses: julia-actions/julia-buildpkg@v1
    - uses: julia-actions/julia-runtest@v1

  action:
    name: Test Github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
      - uses: julia-actions/cache@v1
      - uses: "./"
        with:
          prefix: "cd test/Example.jl &&"

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/cache@v1
      - uses: julia-actions/setup-julia@v1
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
