name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run latest-tag
        uses: EndBug/latest-tag@8b12061830221b438839f7048d1320ac353926aa
